In [1]:
import numpy as np
import pandas as pd

In [2]:
#----------------Ndarray-----------------------

In [11]:
a = np.array([1,5,8,9,6,],dtype = "int64")
a

array([1, 5, 8, 9, 6], dtype=int64)

In [29]:
type(a)

numpy.ndarray

In [12]:
#In order to know the associated dtype to the just created ndarray, you have to use the dtype attribute.
a.dtype

dtype('int64')

In [19]:
#To obtain these values from the corresponding array it is sufficient to use the ndim attribute for getting the axes, the 
#size attribute to know the array length, and the shape attribute to get its shape.

# a.ndim
# a.size
# a.shape

In [22]:
#2-D array
b = np.array([[1.2,2.4],[0.3,5.1]])
print(type(b),b.size,b.ndim,b.shape,b.dtype)

<class 'numpy.ndarray'> 4 2 (2, 2) float64


In [23]:
#Another important attribute is itemsize, which can be used with ndarray objects. It defines the size 
#in bytes of each item in the array,
b.itemsize

8

In [26]:
#------------Create an Array--------------
# b = np.array([[1.2,2.4],[0.3,5.1]])
#The array() function in addition to the lists can accept even tuples and sequences of tuples.
c = np.array(((1,2),(3,4)))
#and also, even sequences of tuples and lists interconnected make no difference.
d = np.array(((1,3),[4,6],(7,9)))
d

array([[1, 3],
       [4, 6],
       [7, 9]])

In [30]:
#----------------------Types of Data---------------
#NumPy arrays are designed to contain a wide variety of data types
e = np.array([["a","b"],["c","d"]])
print(e.dtype,"-----",e.dtype.name)

<U1 ----- str32


In [32]:
#-------------The dtype Option-----------------
#Actually, you can explicitly define the dtype using the dtype option as argument of the function.

In [38]:
f = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="complex")
# df = pd.DataFrame(f)

In [39]:
#----------------Intrinsic Creation of an Array-----------
#The NumPy library provides a set of functions that generate the ndarrays with an initial content, created with 
# some different values depending on the function

In [44]:
#The zeros() function, for example, creates a full array of zeros with dimensions defined by the shape argument.
g = np.zeros((4,3),dtype="int32")
g

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [47]:
#while the ones() function creates an array full of ones in a very similar way.
h = np.ones(shape=(2,5),dtype="int64")
h

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [53]:
#A feature that will be particularly useful is arange(). This function generates NumPy arrays with numerical sequences that 
# respond to particular rules depending on the passed arguments. F
i = np.arange(10)
#OR
#the first is the starting value and the second is the final value.
i = np.arange(4,15)
#If the third argument of the arange() function is specified, this will represent the gap between a value and the next one 
# in the sequence of values.
i = np.arange(0,101,10)
#In addition, this third argument can also be a float.
i = np.arange(0,101,10.1)
i

array([ 0. , 10.1, 20.2, 30.3, 40.4, 50.5, 60.6, 70.7, 80.8, 90.9])

In [58]:
#To generate two-dimensional arrays you can still continue to use the arange() function 
# but combined with the reshape() function.
i = np.arange(1,51).reshape(5,10)
i

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [61]:
# Another function very similar to arange() is linspace(). This function still takes as its first two 
# arguments the initial and end values of the sequence, but the third argument, instead of specifying the 
# distance between one element and the next, defines the number of elements into which we want the interval 
# to be split.
j = np.linspace(0,10,5)
j

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [66]:
# Finally, another method to obtain arrays already containing values is to fill them with random values. 
# This is possible using the random() function of the numpy.random module. This function will generate an 
# array with many elements as specified in the argument.
k = np.array(np.round(np.random.random((4,2))*10,0),dtype="int32")
k

array([[9, 7],
       [6, 3],
       [7, 3],
       [5, 7]])

In [67]:
#-------------------Basic Operations-----------------

In [80]:
#Arithmetic Operators
l = np.arange(1,11)
#Scaler
# l + 2
# l * 2
#B/w 2 array : Element-wise 
a = np.arange(4)
b = np.arange(4,8)
a + b
#Moreover, these operators are also available for functions, provided that the value returned is a NumPy array.
a * np.sin(b)
#Moving on to the multidimensional case, even here the arithmetic operators continue to operate element-wise.
a = np.arange(9).reshape(3,3)
b = np.ones((3,3))
a * 6

array([[ 0,  6, 12],
       [18, 24, 30],
       [36, 42, 48]])

In [83]:
#---------The Matrix Product--------
#dot() function. This operation is not element-wise.
np.dot(a,b)
#An alternative way
a.dot(b)
#OR
a @ b

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [87]:
#-------------------Increment and Decrement Operators-----------------
#instead of creating a new array with the results, they will reassign the results to the same array
a += 2
a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [90]:
#----------------Universal Functions (ufunc)------------
# A universal function, generally called ufunc, is a function operating of an array in an element-by-element 
# fashion. This means that it is a function that acts individually on each single element of the input array to 
# generate a corresponding result in a new output array. At the end, you will obtain an array of the same size of 
# the input.
a = np.arange(10)
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [100]:
#-------------------Aggregate Functions--------------
#Aggregate functions are those functions that perform an operation on a set of values, an array for example, 
# and produce a single result
a = np.array(np.round(np.random.random(10)*10,0),dtype="int32")
print(a)
a.min()
a.max()
a.sum()
a.mean()
a.var()
a.std()

[10  1  2  1  4  6  3  0  5  2]


2.835489375751565

In [101]:
#-------------------------Indexing, Slicing, and Iterating-----------------------

In [104]:
#In order to access a single element of an array you can refer to its index.
a = np.arange(12,19)
print(a)
a[-4]
#To select multiple items at once, you can pass array of indexes within the square brackets.
a[[2,0,5]]

[12 13 14 15 16 17 18]


array([14, 12, 17])

In [105]:
#Moving on to the two-dimensional case, namely, the matrices, they are represented as rectangular 
# arrays consisting of rows and columns, defined by two axes, where axis 0 is represented by the rows and 
# axis 1 is represented by the columns.

In [108]:
a = np.array(np.round(np.random.random((3,3))*10,0),dtype="int32")
print(a)
a[1,2]

[[2 5 4]
 [6 8 3]
 [7 7 8]]


3

In [114]:
#--------------Slicing--------------------
a = np.array(np.round(np.random.random((8,6))*10,0),dtype="int32")
print(a)
# a[start:end:gap]
a[0,:]
# a.flat
# a.flatten()

[[ 2  1  2  6  4  3]
 [ 8  8  5  2  2  1]
 [ 2  8  7  6  3  8]
 [ 2  9  1  1 10  3]
 [ 1  3  8  4  7  9]
 [ 9  7  6  5  5  3]
 [ 3 10  6  4  5  1]
 [ 1  1  1  5  3  3]]


In [115]:
#--------------------Iterating an Array------------------------

In [11]:
#---------------the apply_along_axis() function.
#This function takes three arguments: the aggregate function, the axis on which to apply the iteration, 
# and finally the array. If the option axis equals 0, then the iteration evaluates the elements column by 
# column, whereas if the axis equals 1 then the iteration evaluates the elements row by row.
a = np.array(np.round(np.random.random((3,3))*10,0),dtype="int32")
print(a)
np.apply_along_axis(np.sum,axis=0,arr=a)

[[ 1 10  1]
 [ 6  1  3]
 [ 4  6  6]]


array([11, 17, 10])

In [119]:
#----------------------Conditions and Boolean Arrays-----------------

In [123]:
a = np.random.random((4,4))
a[a < 0.5]

7

In [128]:
#---------------------Shape Manipulation----------------------
a = np.random.random(12)
#returns new array
a.reshape(4,3)
#The reshape() function returns a new array and therefore it is useful to create new objects. However 
# if you want to modify the object by modifying the shape, you have to assign a tuple containing the new 
# dimensions directly to its shape attribute.
a.shape = (3,4)
a

array([[0.01181945, 0.32539378, 0.9374689 , 0.91562878],
       [0.22560535, 0.64753301, 0.56974608, 0.91806714],
       [0.19864356, 0.17321121, 0.16756835, 0.05202825]])

In [132]:
#The inverse operation is possible, that is, to convert a two-dimensional array into a one-dimensional array, 
# through the ravel() function.
a = np.random.random(9).reshape(3,3)
a.ravel()
#or even here acting directly on the shape attribute of the array itself.
a.shape = (9)

In [135]:
#Another important operation is the transposition of a matrix that is an inversion of the columns with 
# rows. NumPy provides this feature with the transpose() function.
a = np.random.random(12).reshape(4,3)
a.transpose()

array([[0.69913972, 0.72763913, 0.76007966, 0.46552643],
       [0.95562237, 0.69316508, 0.04582606, 0.82992082],
       [0.83831946, 0.97089178, 0.87913096, 0.78821075]])

In [136]:
#-----------------Array Manipulation---------------

In [2]:
#--------Joining arrays

In [5]:
a = np.ones((3,3))
b = np.zeros((3,3))

In [9]:
#Vertical Stack
np.vstack((b,a))
#Horizontal stack
np.hstack((b,a))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [17]:
# Two other functions performing stacking between multiple arrays are column_stack() and 
# row_stack(). These functions operate differently than the two previous functions. Generally these functions 
# are used with one-dimensional arrays that are stacked as columns or rows in order to form a new two-dimensional array.
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
#row stack
np.row_stack((a,b,c))
#column stack
np.column_stack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#----------Splitting Arrays---------------

In [21]:
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
#Horizontal Split
[b,c,d,e] = np.hsplit(a,4)
#vertical split
b,c,d,e = np.vsplit(a,4)
print(b[0])
print(c)

[1 2 3 4]
[[5 6 7 8]]


In [33]:
# A more complex command is the split() function, which allows you to split the array into 
# nonsymmetrical parts. In addition, passing the array as an argument, you have also to specify the indexes 
# of the parts to be divided. If you use the option axis = 1, then the indexes will be those of the columns; if 
# instead the option is axis = 0, then they will be the row indexes.

In [36]:
#For row split
a = np.arange(1,17).reshape(4,4)
a1,a2,a3 = np.split(a,[1,3],axis=0)
print(a1,"\n",a2,"\n",a3)

[[1 2 3 4]] 
 [[ 5  6  7  8]
 [ 9 10 11 12]] 
 [[13 14 15 16]]


In [37]:
#-----------------------General Concepts-----------------

In [38]:
#Copies or Views of Objects
a = np.array([1,2,3,4])
b = a
# If you assign one array a to another array b, actually you are not doing a copy but b is just another way to 
# call array a. I
# When you perform the slicing of an array, actually the object returned is only a view of the original array.

In [40]:
# If you want to generate a complete copy and distinct array you can use the copy() function.
a = np.array([1,2,3,4])
b = a.copy()

In [43]:
#------------------Vectorization
# The vectorization is the absence of explicit loop during the developing of the code. These loops actually cannot be omitted,
# but are implemented internally and then they are replaced by other constructs in the code.
#a * b

In [44]:
#----Broadcasting
# Broadcasting is the operation that allows an operator or a function to act on two or more arrays to operate 
# even if these arrays do not have exactly the same shape.

In [45]:
m = np.arange(6).reshape(3, 1, 2)
m

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [46]:
#Reading File with Tabular Data
#data = np.genfromtxt('data.csv', delimiter=',', names=True)